workflows:
  ios-app:
    name: DataPost iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      vars:
        XCODE_PROJECT: "DataPost.xcodeproj"
        XCODE_SCHEME: "DataPost"
        BUNDLE_ID: "org.worldpossible.DataPost"
      xcode: latest
    
    integrations:
      app_store_connect: Codemagic
    
    scripts:
      - name: Set up code signing
        script: |
          echo "=== INITIALIZING KEYCHAIN ==="
          keychain initialize
          
          echo ""
          echo "=== CLEANING UP ORPHANED CERTIFICATES ==="
          # Delete existing distribution certificates we don't have keys for
          for cert_type in IOS_DISTRIBUTION DISTRIBUTION; do
            app-store-connect certificates list --type $cert_type --json 2>/dev/null | \
              python3 -c "import sys, json; certs = json.load(sys.stdin); [print(c['id']) for c in certs]" 2>/dev/null | \
              while read cert_id; do
                echo "Deleting $cert_type certificate: $cert_id"
                app-store-connect certificates delete "$cert_id" 2>/dev/null || true
              done
          done
          
          echo ""
          echo "=== GENERATING FRESH CERTIFICATE KEY ==="
          openssl genrsa -out $CM_BUILD_DIR/cert_key.pem 2048
          export CERTIFICATE_PRIVATE_KEY=$(cat $CM_BUILD_DIR/cert_key.pem)
          
          echo ""
          echo "=== FETCHING/CREATING SIGNING FILES FOR APP STORE ==="
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            -v
          
          echo ""
          echo "=== ADDING CERTIFICATES TO KEYCHAIN ==="
          keychain add-certificates
          
          echo ""
          echo "=== APPLYING PROFILES TO XCODE PROJECT ==="
          xcode-project use-profiles
          
      - name: Build Archive
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/DataPost.xcarchive \
            archive
            
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/DataPost.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist /Users/builder/export_options.plist
    
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $CM_BUILD_DIR/DataPost.xcarchive
      
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - jeremy@worldpossible.org
        notify:
          success: true
          failure: true
