workflows:
  ios-app:
    name: DataPost iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      vars:
        XCODE_PROJECT: "DataPost.xcodeproj"
        XCODE_SCHEME: "DataPost"
        BUNDLE_ID: "org.worldpossible.DataPost"
      xcode: latest
    
    integrations:
      app_store_connect: Codemagic
    
    scripts:
      - name: Set up code signing
        script: |
          echo "=== INITIALIZING KEYCHAIN ==="
          keychain initialize
          
          echo ""
          echo "=== REVOKING ORPHANED CERTIFICATES ==="
          # Get list of existing IOS_DEVELOPMENT certificate IDs and revoke them
          # (we don't have their private keys, so they're useless)
          app-store-connect certificates list --type IOS_DEVELOPMENT --json | \
            python3 -c "import sys, json; certs = json.load(sys.stdin); [print(c['id']) for c in certs]" | \
            while read cert_id; do
              echo "Revoking certificate: $cert_id"
              app-store-connect certificates revoke "$cert_id" || echo "Failed to revoke $cert_id"
            done
          
          echo ""
          echo "=== GENERATING FRESH CERTIFICATE KEY ==="
          openssl genrsa -out $CM_BUILD_DIR/cert_key.pem 2048
          export CERTIFICATE_PRIVATE_KEY=$(cat $CM_BUILD_DIR/cert_key.pem)
          
          echo ""
          echo "=== FETCHING/CREATING SIGNING FILES ==="
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_DEVELOPMENT \
            --create \
            -v
          
          echo ""
          echo "=== ADDING CERTIFICATES TO KEYCHAIN ==="
          keychain add-certificates
          
          echo ""
          echo "=== APPLYING PROFILES TO XCODE PROJECT ==="
          xcode-project use-profiles
          
          echo ""
          echo "=== VERIFY SETUP ==="
          ls -la ~/Library/MobileDevice/Certificates/ 2>/dev/null || echo "No certificates in MobileDevice"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/ 2>/dev/null || echo "No profiles"
          
      - name: Build Archive
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Debug \
            -archivePath $CM_BUILD_DIR/DataPost.xcarchive \
            archive
            
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/DataPost.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist /Users/builder/export_options.plist
    
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $CM_BUILD_DIR/DataPost.xcarchive
      
    publishing:
      email:
        recipients:
          - jeremy@worldpossible.org
        notify:
          success: true
          failure: true
