workflows:
  ios-app:
    name: DataPost iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      vars:
        XCODE_PROJECT: "DataPost.xcodeproj"
        XCODE_SCHEME: "DataPost"
        BUNDLE_ID: "org.worldpossible.DataPost"
      ios_signing:
        distribution_type: development
        bundle_identifier: org.worldpossible.DataPost
      xcode: latest
    
    integrations:
      app_store_connect: Codemagic
    
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_DEVELOPMENT --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build signed IPA
        script: |
          xcodebuild build \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            -archivePath $CM_BUILD_DIR/DataPost.xcarchive \
            clean archive
      - name: Export IPA
        script: |
          xcode-project build-ipa \
            --archive $CM_BUILD_DIR/DataPost.xcarchive
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $CM_BUILD_DIR/DataPost.xcarchive
      
    publishing:
      email:
        recipients:
          - jeremy@worldpossible.org
        notify:
          success: true
          failure: true
